### ISSUE TITLE
[QUESTION]: Please install isilon-sdk

### ISSUE THREAD

**Issue by coloradokb** [dell/ansible-powerscale#57]
### How can the Team help you today?

I'm trying to understand what I could have done, but seemingly out of nowhere, I'm receiving the follower error when running a playbook. Have tried multiple modules (accesszone, filesystem, etc) and receiving:

`Unable to import PowerScale python library. Please install isilon-sdk. Please install the required package(s)`

I have reinstalled isi-sdk-9-1-0 and isi-sdk-8-1-0 and isilon-sdk to no avail. I'm 99% sure I am correctly setting the ANSIBLE_COLLECTIONS_PATHS path too and verifying correct python3 is being used. 

Anyone else seeing this? Thanks!!!

**Comment by anupamaloke** [comment]
@coloradokb, could you please share the output of your playbook run with verbosity turned on (-vvv)?
Also just checking on whether you might have different python version installed on your box? If yes, then one of ways to make sure that you are using the right python binary is by setting the `ansible_python_interpreter` variable to correct python path. For e.g.

```
ansible_python_interpreter: "/usr/bin/env python"
```

**Comment by Javedkhansiddiqui** [comment]
I think you can find some solution here

[](https://www.dell.com/community/Automation/Unable-to-import-PowerScale-python-library-Please-install-isilon/m-p/8411546/thread-id/555#M556)

With the latest ansible module release, the installation of SDK is isilon-sdk(which can be installed using `pip3 install isilon-sdk`) for all versions of onefs instead of version specific sdk installation as in previous releases. Please do let me know of any further clarifications
